### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by krupan** [wenLiangcan/pip2pkgbuild#10]
I'm getting this when I try to run pip2pkgbuild today:

```
Traceback (most recent call last):
  File "/bin/pip2pkgbuild", line 11, in <module>
    load_entry_point('pip2pkgbuild==0.2.3', 'console_scripts', 'pip2pkgbuild')()
  File "/usr/lib/python3.6/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 591, in main
    args.module, args.module_version, args.find_license)
  File "/usr/lib/python3.6/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 525, in fetch_pymodule
    raise e
  File "/usr/lib/python3.6/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 513, in fetch_pymodule
    info = fetch_json(url)
  File "/usr/lib/python3.6/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 509, in fetch_json
    return json.loads(urlopen(url).read().decode('utf-8'))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: SSL is required
```

**Comment by krupan** [comment]
This fixes the problem:
```
diff --git a/pip2pkgbuild/pip2pkgbuild.py b/pip2pkgbuild/pip2pkgbuild.py
index 3372019..4deef01 100644
--- a/pip2pkgbuild/pip2pkgbuild.py
+++ b/pip2pkgbuild/pip2pkgbuild.py
@@ -33,8 +33,8 @@ logging.basicConfig(
 )
 LOG = logging.getLogger('log')
 
-MODULE_JSON = 'http://pypi.python.org/pypi/{name}/json'
-VERSION_MODULE_JSON = 'http://pypi.python.org/pypi/{name}/{version}/json'
+MODULE_JSON = 'https://pypi.python.org/pypi/{name}/json'
+VERSION_MODULE_JSON = 'https://pypi.python.org/pypi/{name}/{version}/json'
 
 MAINTINER_LINE = "# Maintainer: {name} <{email}>\n"
```

**Comment by simon04** [comment]
A PR already has been submitted: https://github.com/wenLiangcan/pip2pkgbuild/pull/9
