### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by douedd** [wenLiangcan/pip2pkgbuild#2]
Hi, thanks for the great tool, it saves a lot of time.

For two packages -- django-model-utils and django-secure -- however I'm encountering the following:

`Traceback (most recent call last):
  File "/usr/bin/pip2pkgbuild", line 9, in <module>
    load_entry_point('pip2pkgbuild==0.1.4', 'console_scripts', 'pip2pkgbuild')()
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 343, in main
    module = fetch_pymodule(args.module, args.module_version)
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 291, in fetch_pymodule
    return PyModule(info)
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 106, in __init__
    self.license = self._get_license(info)
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 124, in _get_license
    lambda recg: recg.lower() == info.get('license', '').lower())
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 121, in find_recognized
    return search_in_iter(recognized_licenses(), p)
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 74, in search_in_iter
    if p(i):
  File "/usr/lib/python3.5/site-packages/pip2pkgbuild/pip2pkgbuild.py", line 124, in <lambda>
    lambda recg: recg.lower() == info.get('license', '').lower())
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by wenLiangcan** [comment]
Thank you for reporting this bug! :) It has been fixed in version 0.1.5 now.

Let me know if you have any other questions or issues.
